language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt --use-mirrors
# command to run tests, e.g. python setup.py test
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "cd webapplication; python server.py &"
  - sleep 3 # give Web server some time to bind to sockets, etc
script:  pybot testsuite
#comment